strategy_name: balanced_strategy
symbol: BTC_USDT
target_base_currency_ratio: 0.5  # Целевая доля BTC в портфеле (0.5 = 50%)
rebalance_threshold: 0.05        # Порог отклонения для ребалансировки (0.05 = 5%)
